### ISSUE TITLE
Please publish this crate

### ISSUE THREAD

**Issue by agalakhov** [carllerche/mio-more#1]
The mio crate references mio-more in its deprecated functions, but mio-more does not exist yet. Please make it available on crates.io.

**Comment by dimbleby** [comment]
see carllerche/mio#573

**Comment by algesten** [comment]
What is the holdup? Isn't it just one single command line to make it happen? Are there doubts?

**Comment by carllerche** [comment]
Released: https://crates.io/crates/mio-more
