### ISSUE TITLE
timeout is not removed from entries after triggering

### ISSUE THREAD

**Issue by yshui** [carllerche/mio-more#6]
Timer::poll_to() does remove the entry, but the sleep thread doesn't

**Comment by dimbleby** [comment]
@yshui this repository is inactive, I'm maintaining a slightly more active fork over at [dimbleby/mio-extras](https://github.com/dimbleby/mio-extras).

If you care to re-raise this issue over there then - well, to be honest, I probably won't do very much with it either.  (I don't myself use the timer function in this crate, and I don't quite follow what problem it is that you are reporting).  

However I would be glad to accept a pull request fixing the problem, if you know how to fix it.  Even more so if accompanied by a test case demonstrating the issue...
